// onix-client/src/templates/Template.svelte
<script lang="ts">
  import SideNav from '../organisms/SideNav.svelte'
</script>

<div class="template">
  <div class="side-nav">
    <SideNav />
  </div>

  <div class="template-slot">
    <slot />
  </div>
</div>

<style>
  .template {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;

    display: flex;
    flex-direction: row;
  }
</style>

// onix-client/src/templates/Template.tsx
import { Box, Divider, Flex } from '@chakra-ui/react'
import styled from '@emotion/styled'
import { Outlet } from 'react-router-dom'
import { SideNav, SideNavItem } from '../organisms/SideNav'

const pages: SideNavItem[] = [
  {
    route: '/',
    text: 'Home',
  },
]

export const FullPageContainer = styled(Flex)`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
`

export const SideNavContainer = styled(Box)`
  height: 100%;
`

export const OutletContainer = styled(Box)`
  padding: 1rem;
`

export const Template = () => {
  return (
    <FullPageContainer direction="row">
      <SideNavContainer>
        <SideNav items={pages} />
      </SideNavContainer>
      <Divider orientation="vertical" />
      <OutletContainer>
        <Outlet />
      </OutletContainer>
    </FullPageContainer>
  )
}
