// onix-client/src/templates/Template.tsx
import { Box, Divider, Flex } from '@chakra-ui/react'
import styled from '@emotion/styled'
import { Outlet } from 'react-router-dom'
import { SideNav, SideNavItem } from '../organisms/SideNav'

const pages: SideNavItem[] = [
  {
    route: '/',
    text: 'Home',
  },
]

export const FullPageContainer = styled(Flex)`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
`

export const SideNavContainer = styled(Box)`
  height: 100%;
`

export const OutletContainer = styled(Box)`
  padding: 1rem;
`

export const Template = () => {
  return (
    <FullPageContainer direction="row">
      <SideNavContainer>
        <SideNav items={pages} />
      </SideNavContainer>
      <Divider orientation="vertical" />
      <OutletContainer>
        <Outlet />
      </OutletContainer>
    </FullPageContainer>
  )
}

// onix-client/src/organisms/Template.tsx
import Stack from '@suid/material/Stack'
import { children, ParentComponent, ParentProps } from 'solid-js'
import { SideNav, SideNavItem } from '../molecules/SideNav'
import { Home } from '@suid/icons-material'
import Box from '@suid/material/Box'
import { styled } from 'solid-styled-components'

const Container = styled(Stack)`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
`

const Slot = styled(Box)`
  padding: 1rem;
`

const navList: SideNavItem[] = [{ icon: <Home />, text: 'Home', uri: '/' }]

export const Template: ParentComponent = (props: ParentProps) => {
  const c = children(() => props.children)

  return (
    <Container direction="row">
      <SideNav navList={navList} />
      <Slot>{c()}</Slot>
    </Container>
  )
}
