// onix-client/src/organisms/SideNav/index.tsx
import { Button, List, ListItem } from '@chakra-ui/react'
import { Route, useNavigate } from '../../router'

export type SideNavProps = {
	items: SideNavItem[]
}

export type SideNavItem = {
	// icon: JSX.Element
	route: Route
	text: string
}

export const SideNav = (props: SideNavProps) => {
	const navigate = useNavigate()

	return (
		<List>
			{props.items.map((item) => (
				<ListItem key={item.route}>
					<Button variant='ghost' onClick={() => navigate(item.route)}>
						{item.text}
					</Button>
				</ListItem>
			))}
		</List>
	)
}

// onix-client/src/molecules/SideNav.tsx
import Box from '@suid/material/Box'
import List from '@suid/material/List'
import ListItem from '@suid/material/ListItem'
import ListItemButton from '@suid/material/ListItemButton'
import ListItemIcon from '@suid/material/ListItemIcon'
import { Component, For, JSX } from 'solid-js'
import { styled } from 'solid-styled-components'
import { Route, useNavigate } from '../Routes'

export type SideNavProps = {
  navList: SideNavItem[]
}

export type SideNavItem = {
  icon: JSX.Element
  text: string
  uri: Route
}

export const Container = styled(Box)`
  background: #081c4c;
  color: #f0f0f4;
`

export const SideNav: Component<SideNavProps> = (props: SideNavProps) => {
  const navigate = useNavigate()

  return (
    <Container>
      <List>
        <For each={props.navList}>
          {(item) => (
            <ListItem disablePadding>
              <ListItemButton onClick={() => navigate(item.uri)}>
                <ListItemIcon>{item.icon}</ListItemIcon>
                {item.text}
                {/* <ListItemText primary={item.text} /> */}
              </ListItemButton>
            </ListItem>
          )}
        </For>
      </List>
    </Container>
  )
}
